version: '3'
services:
  traefik:
    build: .
    command: --docker
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./traefik.toml:/traefik.toml"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=traefik"
      - "traefik.docker.network=web"
      - "traefik.frontend.rule=Host:traefik.localhost"
      - "traefik.port=8080"
    networks:
      - web

networks:
  web:
    external: true
